### ISSUE TITLE
Como usuario autenticado puedo buscar rutinas de ejercicio

### ISSUE THREAD

**Issue by diegoguillen70** [4GeeksAcademy/Vital#4]

**Comment by diegoguillen70** [comment]
Agregue el metodo Fetch para solicitart ejercicios

**Comment by carloscopes** [comment]
Avance de la primera vista de las rutinas

![Image](https://github.com/4GeeksAcademy/Vital/assets/136831607/1d77dc28-60a4-4493-9455-c914a910188e)

**Comment by carloscopes** [comment]
Vista de ejercicios relacionadas a una categoría del cuerpo específica

![Image](https://github.com/4GeeksAcademy/Vital/assets/136831607/06b93182-bae6-4982-ba6b-cfbc7149764d)

**Comment by diegoguillen70** [comment]
excelente

**Comment by diegoguillen70** [comment]
commit 0cb50e3de761b5da6d42dab134fe26015bd9a60b con la vista  https://github.com/4GeeksAcademy/Vital/issues/4#issuecomment-1769858071

**Comment by diegoguillen70** [comment]
I added los Links para navegar en la paginas except Home page.
